{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.persistentVolumeClaim.claimName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agent-job.fullname" . }}-data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
    app.kubernetes.io/component: data
spec:
  accessModes:
    - {{ .Values.persistence.data.persistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.persistentVolumeClaim.storage }}
  {{- if .Values.persistence.data.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.persistence.data.persistentVolumeClaim.storageClassName }}
  {{- else if eq .Values.persistence.data.persistentVolumeClaim.storageClassName "-" }}
  storageClassName: ""
  {{- end }}
{{- end }}

{{- if and .Values.persistence.cache.enabled (not .Values.persistence.cache.persistentVolumeClaim.claimName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agent-job.fullname" . }}-cache
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - {{ .Values.persistence.cache.persistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.persistentVolumeClaim.storage }}
  {{- if .Values.persistence.cache.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.persistence.cache.persistentVolumeClaim.storageClassName }}
  {{- else if eq .Values.persistence.cache.persistentVolumeClaim.storageClassName "-" }}
  storageClassName: ""
  {{- end }}
{{- end }}
