{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agent-job.fullname" . }}-role
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
  {{- with (include "agent-job.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent-job.fullname" . }}-role-binding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
  {{- with (include "agent-job.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agent-job.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "agent-job.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ include "agent-job.fullname" . }}-clusterrole
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
  {{- with (include "agent-job.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .Values.rbac.clusterRules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ include "agent-job.fullname" . }}-clusterrole-binding
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
  {{- with (include "agent-job.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agent-job.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ include "agent-job.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}
