{{- if not .Values.agent.tokenExistingSecret.name }}
apiVersion: v1
data:
  token: {{ required ".Values.agent.token must be provided!" .Values.agent.token | b64enc }}
kind: Secret
metadata:
  name: {{ include "agent-job.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
  {{- $secretAnnotations := merge (deepCopy (default (dict) .Values.global.annotations)) (default (dict) .Values.serviceAccount.annotations) }}
  {{- if not (empty $secretAnnotations) }}
  annotations:
    {{- toYaml $secretAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
{{- end }}
---
{{- if and .Values.global.tls.caBundle (not .Values.global.tls.caBundleSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ca-bundle" (include "agent-job.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
  {{- with (include "agent-job.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.global.tls.caBundleSecret.key }}: {{ .Values.global.tls.caBundle | b64enc }}
{{- end }}
