{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-job.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $saAnnotations := merge (deepCopy (default (dict) .Values.global.annotations)) (default (dict) .Values.serviceAccount.annotations) }}
  {{- if not (empty $saAnnotations) }}
  annotations:
    {{- toYaml $saAnnotations | nindent 4 }}
  {{- end }}
{{- end }}
