apiVersion: v2
name: agent-job
description: |
  A Helm chart for deploying the Scalr Agent on a Kubernetes cluster.
  Uses a controller/worker model. Each run stage is isolated
  in Kubernetes containers with specified resource limits.
type: application
version: 0.5.63
appVersion: 0.56.0
home: https://github.com/Scalr/agent-helm/tree/master/charts/agent-job
maintainers:
  - name: scalr
    email: packages@scalr.com
