apiVersion: v2
name: agent-job
description: |
  A Helm chart for deploying the Scalr Agent on a Kubernetes cluster.
  It uses a job-based model, where each Scalr Run is isolated
  in its own Kubernetes Job.
type: application
version: 0.5.64
appVersion: 0.57.0
home: https://github.com/Scalr/agent-helm/tree/master/charts/agent-job
icon: https://raw.githubusercontent.com/Scalr/agent-helm/master/charts/agent-job/assets/icon.ico
maintainers:
  - name: scalr
    email: packages@scalr.com
sources:
  - https://github.com/Scalr/agent-helm/tree/master/charts/agent-job
