apiVersion: v2
name: agent-local
description: |
  A Helm chart for deploying the Scalr Agent on a Kubernetes cluster.
  Deploys a static number of agents and executes runs in shared agent pods.
type: application
version: 0.5.64
appVersion: 0.60.0
home: https://github.com/Scalr/agent-helm/tree/master/charts/agent-local
maintainers:
  - name: scalr
    email: packages@scalr.com
