apiVersion: v2
name: agent-local
description: |
  A Helm chart for deploying the Scalr Agent on a Kubernetes cluster.
  Best suited for simple deployments and VCS agents.
type: application
version: 0.5.58
appVersion: 0.55.1
home: https://github.com/Scalr/agent-helm/tree/master/charts/agent-local
maintainers:
  - name: scalr
    email: packages@scalr.com
