{{- if not .Values.agent.allowMetadataService }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "agent-local.fullname" . }}-task-network-policy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-local.labels" . | nindent 4 }}
    app.kubernetes.io/component: task
spec:
  podSelector:
    matchLabels:
      {{- include "agent-local.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: task
  policyTypes:
    - Egress
  egress:
    - to:
      - ipBlock:
          # Allow all egress traffic by default
          cidr: 0.0.0.0/0
          except:
            # Deny access to VM metadata service (IMDS)
            - 169.254.169.254/32
{{- end }}
